<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>u_Login</name>
   <tag></tag>
   <elementGuidId>d006d123-a193-40f7-91cd-8925e81e1841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/header/div/div/div/div[3]/div/a/u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>cd985f0a-3599-409e-a66a-9d20f14f60a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>313efb31-61f6-4f2d-9ca1-c8d0b3004bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;header header-layout-3 header__fixed&quot;]/div[@class=&quot;full-width top-bar top-header&quot;]/div[@class=&quot;container-xl&quot;]/div[@class=&quot;container-top-bar&quot;]/div[@class=&quot;top-bar-login&quot;]/div[@class=&quot;d-inline-flex align-items-center&quot;]/a[1]/u[1]</value>
      <webElementGuid>7981429b-2cd0-4090-95a0-de0fc63ae0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/header/div/div/div/div[3]/div/a/u</value>
      <webElementGuid>2f84ace6-35e5-4eb8-9ecf-0aedf8f7d3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='soapleasuremail@gmail.com'])[1]/following::u[1]</value>
      <webElementGuid>076136fa-b882-40e5-94e8-79f267534575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private Custom Soap'])[1]/following::u[1]</value>
      <webElementGuid>4c28fe3b-3ff2-4ab4-8bf8-13ea937f43d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::u[1]</value>
      <webElementGuid>4c2cce6c-4927-4435-a51f-f7f3500c2d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/preceding::u[1]</value>
      <webElementGuid>5a61a59d-aace-46cf-89c4-5b33d228aae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>2fa697fa-00c4-4c9e-905a-f400bfc4e12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>788ab5be-e194-4743-a87e-468c051486bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>84d68c98-c569-4296-9cc1-799c542a5c40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
